name: Postman Tests and Deploy Report
 
on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual trigger
 
jobs:
  test:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
 
      - name: Install Newman & htmlextra reporter
        run: |
          npm install -g newman newman-reporter-htmlextra
 
      - name: Run Postman Collection
        run: |
          mkdir -p report
          newman run DB_Monitoring.postman_collection.json -r htmlextra --reporter-htmlextra-export ./report/index.html
 
      - name: Deploy HTML Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ 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 }}
          publish_dir: ./report
