name: Postman Tests and Deploy Report
 
on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual trigger

permissions:
 contents: write
 
jobs:
  test:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
 
      - name: Install Newman & htmlextra reporter
        run: |
          npm install -g newman newman-reporter-htmlextra
 
      - name: Run Postman Collection (no environment file)
        run: |
         mkdir -p report
         newman run collection.json \
           -r htmlextra \
           --reporter-htmlextra-export ./report/index.html \
           --suppress-exit-code
 
      - name: Deploy HTML Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./report
