name: Run Postman Tests and Publish Report
 
on:
  push:
    branches: [ main ]
  workflow_dispatch:
 
permissions:
  contents: write  # Required to push to gh-pages
 
jobs:
  run-tests:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
 
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
 
      - name: Install Newman and HTML Extra Reporter
        run: |
          npm install -g newman newman-reporter-htmlextra
 
      - name: Run Postman Collection
        run: |
          mkdir -p report
          newman run DB_monitoring.postman_collection.json \
            -r htmlextra \
            --reporter-htmlextra-export ./report/index.html \
            --suppress-exit-code
 
      - name: Deploy HTML report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./report
          publish_branch: gh-pages
          force_orphan: true
